svp=2		#  =  1 - low | 2 - medium (default) | 3 - high
alg=2		#  =  1 - simple | 2 - standard (default) | 3 - complex
fim=2		#  =  1 - average | 2 - adaptive (default) | 3 - uniform
bf=0		#  =  0 - off (default) | 1 - blending frames
sh=0		#  =  0 - off (default) | 1 - avisynth sharpness
uhd=0		#  =  0 - off (default) | 1 - ultra hd video support
gpu=0		#  =  0 - off (default) | 1 - first gpu | 2 - second gpu
fps=60		#  =  60 (default) | 2 - x2 fps | 50 ... 120 - target fps

import("svp.avs")	#  medium smoothness quality | medium cpu load